blog/blog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_view

from core.views import index, topic_details

urlpatterns = [
    path('login/', auth_view.LoginView.as_view()),
    path('index/', index, name='index'),
    path(r'topic/(?P<pk>\d+)/$', topic_details, name='topic_details'),
    path('admin/', admin.site.urls),
    path('feedback/', include('feedback.urls')),
]

blog/feedback/urls.py
from django.contrib import admin
from django.urls import include, path
from core.views import index, topic_details
from feedback.views import FeedbackCreateView, FeedbackListView

urlpatterns = [
    path('add', FeedbackCreateView.as_view(), name='feedback-create'),
    path('', FeedbackListView.as_view(), name='feedback-list'),
]

blog/formdum/urls.py
from django.contrib import admin
from django.urls import include, path
from core.views import index, topic_details
from formdum.views import MarshView

urlpatterns = [
    path('', MarshView.as_view()),
]

blog/core/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=255)


class Topic(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    categories = models.ManyToManyField(Category, related_name='topics')

blog/feedback/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Feedback(models.Model):
    text = models.CharField(verbose_name='Отзыв', max_length=5000)
    grade = models.IntegerField(verbose_name='Оценка')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    subject = models.CharField(verbose_name='Объект', max_length=100)

blog/feedback/forms.py
from django.forms import Form
from django import forms


class DummForm(Form):
    text = forms.CharField(label='Отзыв', max_length=10, min_length=3)
    grade = forms.IntegerField(label='Оценка', max_value=10, min_value=1)
    image = forms.FileField(label='Фото', required=False)

blog/core/views.py
from django.db.models import Count
from django.shortcuts import render
from django.http import HttpResponse, Http404
from core.models import Topic, Category


# Create your views here.
def index(request):
    topics = Topic.objects.all().annotate(Count('categories'))
    categories = Category.objects.all()

    q = request.GET.get('q')
    if q is not None:
        topics = topics.filter(title__icontains=q)
    category_pk = request.GET.get('category')
    if category_pk is not None:
        topics = topics.filter(categories__pk=category_pk)
    return render(request, 'core/index.html', context={
        'topics': topics,
        'categories': categories
    })


def topic_details(request, pk):
    try:
        topic = Topic.objects.get(pk=pk)
    except Topic.DoesNotExist:
        raise Http404
    return render(request, 'core/topic_details.html', context={
        'topic': topic
    })

blog/feedback/views.py
from django.shortcuts import render
import json
from django.http import JsonResponse
from django.views import View
from django.views.generic.edit import CreateView
from django.views.generic import ListView
from jsonschema import validate
from jsonschema.exceptions import ValidationError
from feedback.forms import DummForm
from feedback.schemas import REVIEW_SCHEMA, ReviewSchema
from django.contrib.auth.mixins import LoginRequiredMixin
from marshmallow.exceptions import ValidationError as MarshError
from .models import Feedback


# Create your views here.
class FeedbackCreateView(LoginRequiredMixin, CreateView):
    model = Feedback
    fields = ['text', 'grade', 'subject']
    success_url = '/feedback/add'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class FeedbackListView(LoginRequiredMixin, ListView):
    model = Feedback

    def get_queryset(self):
        if self.request.user.is_staff:
            return Feedback.objects.all()
        return Feedback.objects.filter(author=self.request.user)

class SchemaView(View):
    def post(self, request):
        try:
            document = json.loads(request.body)
            validate(document, REVIEW_SCHEMA)
            return JsonResponse(document, status=201)
        except json.JSONDecodeError:
            return JsonResponse({'errors': 'Invalid JSON'}, status=400)
        except ValidationError as exc:
            return JsonResponse({'errors': exc.message}, status=400)


class MarshView(View):
    def post(self, request):
        try:
            document = json.loads(request.body)
            schema = ReviewSchema(strict=True)
            data = schema.load(document)
            return JsonResponse(data, status=201)
        except json.JSONDecodeError:
            return JsonResponse({'errors': 'Invalid JSON'}, status=400)
        except MarshError as exc:
            return JsonResponse({'errors': exc.messages}, status=400)

blog/formdum/views.py
from django.shortcuts import render
import json
from django.http import JsonResponse
from django.views import View
from jsonschema import validate
from jsonschema.exceptions import ValidationError
from formdum.forms import DummForm
from formdum.schemas import REVIEW_SCHEMA, ReviewSchema
from marshmallow.exceptions import ValidationError as MarshError


# Create your views here.
class FormDummView(View):
    def get(self, request):
        form = DummForm()
        return render(request, 'form.html', context={
            'form': form
        })

    def post(self, request):
        form = DummForm(request.POST)
        if form.is_valid():
            context = form.cleaned_data
            return render(request, 'form.html', context)
        else:
            return render(request, 'error.html', {'errors': form.errors})


class SchemaView(View):
    def post(self, request):
        try:
            document = json.loads(request.body)
            validate(document, REVIEW_SCHEMA)
            return JsonResponse(document, status=201)
        except json.JSONDecodeError:
            return JsonResponse({'errors': 'Invalid JSON'}, status=400)
        except ValidationError as exc:
            return JsonResponse({'errors': exc.message}, status=400)


class MarshView(View):
    def post(self, request):
        try:
            document = json.loads(request.body)
            schema = ReviewSchema(strict=True)
            data = schema.load(document)
            return JsonResponse(data, status=201)
        except json.JSONDecodeError:
            return JsonResponse({'errors': 'Invalid JSON'}, status=400)
        except MarshError as exc:
            return JsonResponse({'errors': exc.messages}, status=400)

blog/core/templates/core/category.html
<div class="category">
    {% for category in categories %}
        <div class="category__item">
            <a href="{% url 'index' %}?category = {{ category.pk }}">{{ category.title }}</a>
        </div>
    {% endfor %}
</div>

blog/core/templates/core/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Index{% endblock %}
{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'core/css/index.css' %}">
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-8">
            {% include 'core/topic_list.html' %}
        </div>
        <div class="col-4">
            {% include 'core/category.html' %}
        </div>
    </div>
</div>
{% endblock %}

blog/core/templates/core/topic_details.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'core/css/index.css' %}">
{% endblock %}
{% block content %}
<div class="container">
    <div class="topic">
        <h4><a href="#">{{ topic.title }}</a></h4>
        <h6>Категория ({{ topic.categories.count }}): {% for category in topic.categories.all %}
            {{ category.title }}{% if not forloop.last %}, {% endif %}
            {% endfor %}</h6>
        <p>{{ topic.body }}</p>
    </div>
</div>
{% endblock %}

blog/core/templates/core/topic_list.html
{% load static %}
<div class="topic-list">
    {% for topic in topics %}
        <div class="topic-list__item">
            <h4><a href="#">{{ topic.title }}</a></h4>
            <h6>Категория ({{ topic.categories__count }}): {% for category in topic.categories.all %}
                {{ category.title }}{% if not forloop.last %}, {% endif %}
                {% endfor %}</h6>
            <p>{{ topic.body }}</p>
            <a href="{% url 'topic_details' topic.pk %}" class="btn btn-outline-info">More</a>
        </div>
    {% endfor %}

</div>

blog/feedback/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Ошибка</h1>
</body>
</html>

blog/feedback/templates/feedback/feedback_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Feedback Form</title>
</head>
<body>
<h1>Feedback Form</h1>
<form method="post" enctype="multipart/form-data" action="/feedback/add">
    {% csrf_token %}
    {{ form }}
    <input id="feedback-submit" type="submit">
</form>
</body>
</html>

blog/feedback/templates/feedback/feedback_list.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Отзывы</title>
</head>
<body>
<h1>Отзывы</h1>
{% for feedback in object_list %
<li>{{ feedback.subject }} - {{{ feedback.text }}</li>
{% empty %}
<li>Нет отзывов.</li>
{% endfor %}
</body>
</html>

blog/feedback/templates/feedback/feedbackform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Feedback Form</title>
</head>
<body>
<h1>Feedback Form</h1>
<form method="post" enctype="multipart/form-data" action="/feedback/add">
    {% csrf_token %}
    {{ form }}
    <input id="feedback-submit" type="submit">
</form>
</body>
</html>

blog/feedback/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<h1>Feedback Form</h1>
<form method="post" enctype="multipart/form-data" action="/form/">
    {% csrf_token %}
    {{ form }}
    <input id="feedback-submit" type="submit">
</form>
</body>
</html>

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    {% block styles %}{% endblock %}

    <script type="text/javascript" src="{% static 'jquery/jquery-3.6.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% block scripts %} {% endblock %}
</head>
<body>
<div>
    {% block nav %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">Blog</a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">News</a>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" formaction="{% url 'index' %}" type="search" placeholder="Search"
                           aria-label="Search" name="q">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    {% endblock %}
    {% block content %}{% endblock %}
</div>
</body>
</html>